# Server
server:
  port: 9090

# Spring
spring:
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: root
    password: root

# Flyway
  flyway:
    url: jdbc:h2:mem:db
    user: root
    password: root

# Jpa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

# H2
  h2:
    console:
      enabled: true
      path: /h2